// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ComponentEntry is a single searchable item (a symbol or a design block) found
 * by scanning the registered library repositories on disk.
 */
export class ComponentEntry {
    /**
     * Creates a new ComponentEntry instance.
     * @param {Partial<ComponentEntry>} [$$source = {}] - The source object to create the ComponentEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "Symbol" | "Design Block"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("repo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repo"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("keywords" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keywords"] = "";
        }
        if (!("reference" in $$source)) {
            /**
             * KiCad library reference: nickname:name
             * @member
             * @type {string}
             */
            this["reference"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComponentEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComponentEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComponentEntry(/** @type {Partial<ComponentEntry>} */($$parsedSource));
    }
}

/**
 * Config represents the user's saved settings
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("baseLibPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseLibPath"] = "";
        }
        if (!("watchDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["watchDir"] = "";
        }
        if (!("repositories" in $$source)) {
            /**
             * @member
             * @type {Repository[]}
             */
            this["repositories"] = [];
        }
        if (!("categories" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["categories"] = [];
        }
        if (!("history" in $$source)) {
            /**
             * @member
             * @type {HistoryItem[]}
             */
            this["history"] = [];
        }
        if (!("autoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoStart"] = false;
        }
        if (!("defaultRepo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultRepo"] = "";
        }
        if (!("autoCategoryMap" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["autoCategoryMap"] = {};
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastUpdateCheck"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dismissedUpdateVersion"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType4;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repositories" in $$parsedSource) {
            $$parsedSource["repositories"] = $$createField2_0($$parsedSource["repositories"]);
        }
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField3_0($$parsedSource["categories"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField4_0($$parsedSource["history"]);
        }
        if ("autoCategoryMap" in $$parsedSource) {
            $$parsedSource["autoCategoryMap"] = $$createField7_0($$parsedSource["autoCategoryMap"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * DuplicateInfo describes an existing library location that already contains a
 * symbol with the same name as an incoming part (shown as an import warning).
 */
export class DuplicateInfo {
    /**
     * Creates a new DuplicateInfo instance.
     * @param {Partial<DuplicateInfo>} [$$source = {}] - The source object to create the DuplicateInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("repo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repo"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DuplicateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DuplicateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DuplicateInfo(/** @type {Partial<DuplicateInfo>} */($$parsedSource));
    }
}

/**
 * HistoryItem tracks an integration event for undo purposes
 */
export class HistoryItem {
    /**
     * Creates a new HistoryItem instance.
     * @param {Partial<HistoryItem>} [$$source = {}] - The source object to create the HistoryItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("repoName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repoName"] = "";
        }
        if (!("addedFiles" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["addedFiles"] = [];
        }
        if (!("symbolMaster" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["symbolMaster"] = "";
        }
        if (!("symbolBackup" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["symbolBackup"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryItem}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("addedFiles" in $$parsedSource) {
            $$parsedSource["addedFiles"] = $$createField5_0($$parsedSource["addedFiles"]);
        }
        return new HistoryItem(/** @type {Partial<HistoryItem>} */($$parsedSource));
    }
}

/**
 * Repository represents a single Git library
 */
export class Repository {
    /**
     * Creates a new Repository instance.
     * @param {Partial<Repository>} [$$source = {}] - The source object to create the Repository.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Repository instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Repository}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Repository(/** @type {Partial<Repository>} */($$parsedSource));
    }
}

/**
 * UpdateInfo is returned to the frontend to drive the "update available" modal.
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("hasUpdate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasUpdate"] = false;
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("releaseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Repository.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = HistoryItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $$createType2);
