name: Build Windows App
on: 
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install Wails v3
        run: go install -v github.com/wailsapp/wails/v3/cmd/wails3@v3.0.0-alpha2.103

      - name: Build Application
        run: wails3 task build PLATFORM=windows CONFIG=production

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: bin/ # This will likely contain a .exe file